---
- name: Prompt user for installation choice
  hosts: localhost
  vars_files: vars/main.yml


  # 1. Determine correct configuration to launch into (user prompt)
  # 2. Ensure dependencies are met
  tasks:
    - name: Include the appropriate playbook based on selection
      ansible.builtin.include_playbook: "{{ item }}"
      loop:
        - "personal.yml"
        - "work.yml"
        - "server.yml"
      when: 
        - (selected_option == "1" and item == "personal.yml") or
          (selected_option == "2" and item == "work.yml") or
          (selected_option == "3" and item == "server.yml")

